apiVersion: v1
kind: Secret
metadata:
  name: 88-api-secret
  namespace: 88-api
type: Opaque
data:
  # Base64 encoded values - replace with your actual secrets
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWhlcmU=  # "your-jwt-secret-here" in base64
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # "password" in base64
stringData:
  # Non-base64 encoded values
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  DATABASE_PASSWORD: "password" 